### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "cr12@gmail.com",
    "password": "12312345"
}

### sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "ronaldo",
    "lastName": "cristiano",
    "email": "cr12@gmail.com",
    "password": "12312345"
}


### profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNyMTJAZ21haWwuY29tIiwic3ViIjoxOSwiaWF0IjoxNzQyNDc1NDA2LCJleHAiOjE3NDI1NjE4MDZ9.JqcKJDFEk3Ki_UxG_H_NzVexYHIpEn5AFJdM3hYtigQ
