GET http://localhost:3000
### TEST
POST http://localhost:3000
### GET ALL SONGS
GET http://localhost:3000/songs

### GET SONG BY ID
GET http://localhost:3000/songs/3

### POST SONG
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "LM10",
    "artists": [
        "LM10"
    ],
    "releasedDate": "2024-04-04",
    "duration": "02:34",
    "lyrics": "DSADASDDSA"
}

### CHANGE SONG
PUT http://localhost:3000/songs/5
Content-Type: application/json

{
    "title": "CR7",
    "artists": [
        "CR7"
    ],
    "releasedDate": "2024-04-04",
    "duration": "02:34",
    "lyrics": "DSADASDDSA"
}
### DELETE SONG
DELETE http://localhost:3000/songs/2